name: deepdrr_zmq
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - pytorch-cuda=11.7
  # - cudatoolkit=11.1
  - pycuda
  - pip
  - pip:
      # - -r requirements.txt
      - deepdrr
      - pyzmq
      - pycapnp
      - typer
      # - -e .
