name: deepdrr_zmq
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pycuda
  - pip
  - pip:
      - deepdrr==1.1.2
      - pyzmq
      - pycapnp
      - typer
      - scipy
      - joblib
      - pipenv
